### ISSUE TITLE
Consider a non-generic `\Exception`

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#10]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/src/DragonPay/DragonPayService.php#L71

A `TendoPay\Integration\Exception\DragonPayException` maybe? That might not be the best suggestion.

My reason is that I might want to see this type of exception vs. some other generic one (and I don't want to get exception message scraping if I can avoid it).

**Comment by robklo** [comment]
I see you point. I totally agree with you. Will change this.
