### ISSUE TITLE
Consider `using` All The Classes

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#15]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/src/DragonPay/SoapClient/DragonPayClient.php#L10

e.g.

```
    /**
     * @param RequestInterface|Type\GetCountries $parameters
     * @return ResultInterface|Type\GetCountriesResponse
     * @throws SoapException
     */
    public function getCountries(GetCountries $parameters) : GetCountriesResponse
    {
        return $this->call('GetCountries', $parameters);
    }
```

It also brings the long lines down.

**Comment by robklo** [comment]
This is autogenerated code. I will consider moving these files under `autogenerated` folder, just to make it obvious, but I don't want to beautify autogenerated code.
