### ISSUE TITLE
Wrong NL - this shouldn't be on a new line

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#17]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/src/DragonPay/SoapClient/Type/SplitPayment.php#L109

**Comment by robklo** [comment]
This is autogenerated code. I will consider moving these files under `autogenerated` folder, just to make it obvious, but I don't want to beautify autogenerated code.
