### ISSUE TITLE
PHP Storm is Complaining Return Value is Wrong

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#18]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/src/DragonPay/SoapClient/DragonPayClientFactory.php#L19

So it probably is.

"Return value is not compatible with declared."

**Comment by robklo** [comment]
this is autogenerated code and generally I'd rather not touch that code. However I'll make an exception for this particular issue

**Comment by lloy0076** [comment]
Thanks.
