### ISSUE TITLE
`soap-client.php` - a little too generic

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#2]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/config/soap-client.php#L1

Not that I think this is likely to clash with something else but `soap-client.php` is a little generic.

**Comment by robklo** [comment]
This is auto-generated code. We probably don't even use it.
