### ISSUE TITLE
Please Comment What That Is

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#3]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/config/soap-client.php#L11

It wasn't obvious to me that this was setting some type of SOAP client configuration (as there is a a `Config::` facade too).

Please make some sort of comment about what this is trying to achieve.

**Comment by robklo** [comment]
This is auto-generated code and I'm pretty sure we don't use it. Maybe the whole directory of autogenerated code should be moved under `autogenerated` folder? 🤔
