### ISSUE TITLE
Make this Configurable - Maybe?

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#4]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/config/soap-client.php#L12

This particular line seems to be the one that probably should be easily configurable; maybe? That `test...` looks like it's the one that might need changing? Not sure.

**Comment by robklo** [comment]
I'm pretty sure we don't use the `soap-client.php` at all. I'll just remove that file and check if the integration works.
