### ISSUE TITLE
Should Name Have a Length?

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#5]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/migrations/2018_09_06_000000_create_user_lifetime_ids_table.php#L21

**Comment by robklo** [comment]
it should. What is the customer name length in TP database? let's make it something similar

**Comment by lloy0076** [comment]
No idea. Probably no more than 25; let me look when I gave better access.
