### ISSUE TITLE
Please Call Ourselves `dragonpay_`

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#6]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/migrations/2018_09_06_000000_create_user_lifetime_ids_table.php#L17

Personally I think we should give this thing a full name in the database.

**Comment by robklo** [comment]
It would be easier to just change the name in this migration rather than adding a new migration. Although if you already did the migrations I shouldn't change it. 

Please let me know how should I fix it.

**Comment by lloy0076** [comment]
Consider it carte blanche ATM. I'll a ninja at docking it of the way of Laravel migrations.

Ups he inclined to fo it the easiest way.

**Comment by robklo** [comment]
Not sure if I understood it all properly 😆  but I think you mean that I can choose my way.

Changing the table name would require writing raw SQL query.

**Comment by lloy0076** [comment]
Thanks.
