### ISSUE TITLE
What About `created_at` and `updated_at`?

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#7]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/src/DragonPay/Model/DragonPayUserLifetimeId.php#L36

**Comment by robklo** [comment]
True, will add it too.

**Comment by lloy0076** [comment]
Thanks.
