### ISSUE TITLE
Die On Construct - Not Here?

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/laravel-dragonpay-api#9]
https://github.com/TendoPayPlugins/laravel-dragonpay-api/blob/c1333098c881a3008bb47a977b4503337e21ee26/src/DragonPay/DragonPayService.php#L54

I wonder if it's better to die when we construct this thing (i.e. in `__construct`) rather than here?

**Comment by robklo** [comment]
You're probably right. I would just throw an exception. What do you think?

**Comment by lloy0076** [comment]
Thanks.
